<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Available variables' => 'Доступные переменные',
    'Send mails' => 'Отправка почты',
    'Description' => 'Описание',
    'Email of the current recipient of the letter' => 'Электронная почта получателя письма',
    'Following variables could be used in the mail body and subject in form <code>{variable_name}</code>' => 'Переменные ниже могут быть использованы в теле письма и в теме в следующем виде <code>{имя_переменной}</code>',
    'ID' => '',
    'Receiver Data' => 'Данные получателей',
    'Receivers type' => 'Тип получателей',
    'Variable' => 'Переменная',
    'Body Html' => 'HTML-текст',
    'Change of this field will reload current page' => 'Изменение этого поля приведет к перезагрузке страницы',
    'Create & Send!' => 'Создать и отправить!',
    'Created At' => 'Дата создания',
    'Emails' => 'Электронные адреса',
    'From' => 'Email отправителя',
    'From Name' => 'Имя отправителя',
    'Mail' => 'Письмо',
    'Mailing module' => 'Модуль отправки писем',
    'Mails' => 'Письма',
    'Mails are placed in the queue and will be sent soon' => 'Почтовые сообщения добавлены в очередь и скоро будут отправлены',
    'Mails were successfully sent' => 'Почтовые сообщения успешно отправлены',
    'Manual receiver' => 'Отдельный получатель почты',
    'New' => 'Новое',
    'Receiver' => 'Получатель',
    'Save & Send!' => 'Сохранить и отправить!',
    'Sending' => 'Происходит отправка',
    'Sending emails' => 'Отправка почты',
    'Sent' => 'Отправлено',
    'Sent At' => 'Дата отправки',
    'Status' => 'Статус',
    'Subject' => 'Тема письма',
    'Waiting for sending' => 'Ожидает отправки',
    'You can set multiple emails separated by <code>;</code> symbol' => 'Вы можете указать несколько адресов, разделенных символом <code>;</code>',
];
